#!/usr/bin/env bash 

# create a vpc 

VPC_ID=$(aws ec2 create-vpc --cidr-block "172.16.0.0/16" \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-1}]' \
--region us-east-1  \
--query Vpc.VpcId \
--output text)

echo "VPC_ID : $VPC_ID"

#Turn on  Dns Hostnames 

aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames 
# create an IGW 

IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text)

echo "IGW_ID : $IGW_ID"

# Attach an IGW 

aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID
# create a new subnet 

SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID \
--cidr-block 172.16.1.0/24 \
--query Subnet.SubnetId \
--output text)

echo "Subnet_Id : $SUBNET_ID"

# Auto assign ipv4 addresses

aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch 

# explicitly associate a subnet 

RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[].RouteTableId[]" \
--output text
)

echo "RT_ID : $RT_ID"


aws ec2 associate-route-table --route-table-id $RT_ID --subnet-id $SUBNET_ID

# add a route for our RT to IGW

aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID


