#!/usr/bin/env bash 


# CHECK if the argument is not provided 

if [ -z "$1" ]; then 
    echo "Argument is not provided."
else 
    export VPC_ID="$1"
fi 

# Detach Internet gateway 

aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Delete Internet gateway 

# Delete vpc 

aws ec2 delete-vpc --vpc-id $VPC_ID

